image: archlinux
repositories:
  sr.ht: https://mirror.sr.ht/sr.ht/archlinux/#1ED4E14494433AE3FD302CAB74B4BCCEA60D0437
packages:
  - npm
  - sassc
  - python-setuptools
  - python-flask
  - python-humanize
  - python-sqlalchemy
  - python-sqlalchemy-utils
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/srht
  - https://git.sr.ht/~sircmpwn/sr.ht-pkgbuilds
environment:
  repo_server: deploy@mirror.sr.ht
  repo_path: /var/html/mirror/sr.ht/archlinux
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018 # ssh deploy key
  - 3e65a1a8-a20f-4f6b-a452-df2ac398bc1e # package signing key
tasks:
  - build: |
      cd srht
      ./setup.py build
  - archive: |
      cd srht
      pkgver=$(git describe | sed -e 's/-/_/g')
      echo "pkgver=$pkgver" >> ~/.buildenv
      git archive -o ~/sr.ht-pkgbuilds/python-srht/srht-$pkgver.tar.xz \
        --prefix=srht-$pkgver/ HEAD
  - package: |
      cd sr.ht-pkgbuilds/python-srht
      _ver=$(pacman -Si python-srht | grep Version | cut -d':' -f2 | sed -e 's/^ *//')
      _prevver=$(echo "$_ver" | cut -d'-' -f1)
      _prevrel=$(echo "$_ver" | cut -d'-' -f2)
      pkgrel=1
      [ "$_prevver" == "$pkgver" ] && pkgrel=$(expr $_prevrel + 1)
      sed -e "s/pkgver=.*/pkgver=$pkgver/" -i PKGBUILD
      sed -e "s/pkgrel=.*/pkgrel=$pkgrel/" -i PKGBUILD
      echo "pkgrel=$pkgrel" >> ~/.buildenv
      updpkgsums
      makepkg --config ../makepkg.conf -s --noconfirm
      cd ~/srht
      git describe --exact-match HEAD || complete-build
  - publish: |
      cd sr.ht-pkgbuilds/python-srht
      sshopts="-o StrictHostKeyChecking=no" # TODO: remove this when builds run on a tty
      rsync --rsh="ssh $sshopts" -rP *.pkg.tar.xz{,.sig} $repo_server:$repo_path/
      ssh $sshopts $repo_server repo-add -n -R \
        $repo_path/sr.ht.db.tar.gz \
        $repo_path/python-srht-$pkgver-$pkgrel-any.pkg.tar.xz
