#!/usr/bin/env python3
import base64
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization

private_key = Ed25519PrivateKey.generate()
private_key_b = private_key.private_bytes(
        format=serialization.PrivateFormat.Raw,
        encoding=serialization.Encoding.Raw,
        encryption_algorithm=serialization.NoEncryption())
print("Private key: " + base64.b64encode(private_key_b).decode())

public_key = private_key.public_key()
public_key_b = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw)
print("Public key: " + base64.b64encode(public_key_b).decode())
